apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30008  # Make sure this field is properly indented and placed within the 'ports' section.
selector:
  app: example
